html_title: "Solutions"
page_title: "Solutions"

solutions:
  - title: "Commercial Refrigerated Cabinets"
    link: "tw/applications/story1"
    description: "Description for Commercial Refrigerated Cabinets"
    image: "images/solution/supermarket_app.png"

  - title: "Vending Machine"
    link: "tw/applications/story2"
    description: "Description for Vending Machine"
    image: "images/solution/supermarket_app.png"

  - title: "Charging Station"
    link: "tw/applications/story3"
    description: "Description for Charging Station"
    image: "images/solution/supermarket_app.png"

  - title: "Meter Reading"
    link: "tw/applications/story4"
    description: "Description for Meter Reading"
    image: "images/solution/supermarket_app.png"

  - title: "Self Gas Station"
    link: "tw/applications/story5"
    description: "Description for Self Gas Station"
    image: "images/solution/supermarket_app.png"

  - title: "Solar Power Plants"
    link: "tw/applications/story6"
    description: "Description for Solar Power Plants"
    image: "images/solution/supermarket_app.png"
